export type SEOLocation = {
  slug: string;
  name: string;
  type: 'state' | 'university' | 'city' | 'role' | 'company' | 'country' | 'keyword';
};

export const seoLocations: SEOLocation[] = [
  // ── INTERNATIONAL COUNTRIES ──
  { slug: 'united-states', name: 'United States', type: 'country' },
  { slug: 'united-kingdom', name: 'United Kingdom', type: 'country' },
  { slug: 'canada', name: 'Canada', type: 'country' },
  { slug: 'australia', name: 'Australia', type: 'country' },
  { slug: 'uae', name: 'United Arab Emirates', type: 'country' },
  { slug: 'singapore', name: 'Singapore', type: 'country' },
  { slug: 'germany', name: 'Germany', type: 'country' },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', type: 'country' },
  { slug: 'france', name: 'France', type: 'country' },
  { slug: 'india', name: 'India', type: 'country' },
  { slug: 'malaysia', name: 'Malaysia', type: 'country' },
  { slug: 'nigeria', name: 'Nigeria', type: 'country' },
  { slug: 'south-africa', name: 'South Africa', type: 'country' },
  { slug: 'new-zealand', name: 'New Zealand', type: 'country' },
  { slug: 'ireland', name: 'Ireland', type: 'country' },
  { slug: 'netherlands', name: 'Netherlands', type: 'country' },
  { slug: 'sweden', name: 'Sweden', type: 'country' },
  { slug: 'switzerland', name: 'Switzerland', type: 'country' },
  { slug: 'italy', name: 'Italy', type: 'country' },
  { slug: 'japan', name: 'Japan', type: 'country' },
  { slug: 'south-korea', name: 'South Korea', type: 'country' },
  { slug: 'philippines', name: 'Philippines', type: 'country' },
  { slug: 'pakistan', name: 'Pakistan', type: 'country' },
  { slug: 'bangladesh', name: 'Bangladesh', type: 'country' },
  { slug: 'sri-lanka', name: 'Sri Lanka', type: 'country' },
  { slug: 'ghana', name: 'Ghana', type: 'country' },
  { slug: 'kenya', name: 'Kenya', type: 'country' },
  { slug: 'qatar', name: 'Qatar', type: 'country' },
  { slug: 'kuwait', name: 'Kuwait', type: 'country' },
  { slug: 'bahrain', name: 'Bahrain', type: 'country' },
  { slug: 'oman', name: 'Oman', type: 'country' },

  // ── INDIAN STATES ──
  { slug: 'andhra-pradesh', name: 'Andhra Pradesh', type: 'state' },
  { slug: 'telangana', name: 'Telangana', type: 'state' },
  { slug: 'maharashtra', name: 'Maharashtra', type: 'state' },
  { slug: 'karnataka', name: 'Karnataka', type: 'state' },
  { slug: 'tamil-nadu', name: 'Tamil Nadu', type: 'state' },
  { slug: 'delhi-ncr', name: 'Delhi NCR', type: 'state' },
  { slug: 'uttar-pradesh', name: 'Uttar Pradesh', type: 'state' },
  { slug: 'gujarat', name: 'Gujarat', type: 'state' },
  { slug: 'west-bengal', name: 'West Bengal', type: 'state' },
  { slug: 'rajasthan', name: 'Rajasthan', type: 'state' },
  { slug: 'madhya-pradesh', name: 'Madhya Pradesh', type: 'state' },
  { slug: 'kerala', name: 'Kerala', type: 'state' },
  { slug: 'punjab', name: 'Punjab', type: 'state' },
  { slug: 'haryana', name: 'Haryana', type: 'state' },
  { slug: 'bihar', name: 'Bihar', type: 'state' },
  { slug: 'odisha', name: 'Odisha', type: 'state' },
  { slug: 'assam', name: 'Assam', type: 'state' },
  { slug: 'jharkhand', name: 'Jharkhand', type: 'state' },
  { slug: 'chhattisgarh', name: 'Chhattisgarh', type: 'state' },
  { slug: 'uttarakhand', name: 'Uttarakhand', type: 'state' },
  { slug: 'himachal-pradesh', name: 'Himachal Pradesh', type: 'state' },
  { slug: 'goa', name: 'Goa', type: 'state' },
  { slug: 'manipur', name: 'Manipur', type: 'state' },
  { slug: 'meghalaya', name: 'Meghalaya', type: 'state' },
  { slug: 'tripura', name: 'Tripura', type: 'state' },
  { slug: 'nagaland', name: 'Nagaland', type: 'state' },

  // ── GLOBAL CITIES ──
  { slug: 'hyderabad', name: 'Hyderabad', type: 'city' },
  { slug: 'bangalore', name: 'Bangalore', type: 'city' },
  { slug: 'mumbai', name: 'Mumbai', type: 'city' },
  { slug: 'pune', name: 'Pune', type: 'city' },
  { slug: 'chennai', name: 'Chennai', type: 'city' },
  { slug: 'delhi', name: 'Delhi', type: 'city' },
  { slug: 'noida', name: 'Noida', type: 'city' },
  { slug: 'gurugram', name: 'Gurugram', type: 'city' },
  { slug: 'ahmedabad', name: 'Ahmedabad', type: 'city' },
  { slug: 'kolkata', name: 'Kolkata', type: 'city' },
  { slug: 'jaipur', name: 'Jaipur', type: 'city' },
  { slug: 'lucknow', name: 'Lucknow', type: 'city' },
  { slug: 'bhopal', name: 'Bhopal', type: 'city' },
  { slug: 'indore', name: 'Indore', type: 'city' },
  { slug: 'nagpur', name: 'Nagpur', type: 'city' },
  { slug: 'coimbatore', name: 'Coimbatore', type: 'city' },
  { slug: 'kochi', name: 'Kochi', type: 'city' },
  { slug: 'visakhapatnam', name: 'Visakhapatnam', type: 'city' },
  { slug: 'vijayawada', name: 'Vijayawada', type: 'city' },
  { slug: 'tirupati', name: 'Tirupati', type: 'city' },
  { slug: 'warangal', name: 'Warangal', type: 'city' },
  { slug: 'bhubaneswar', name: 'Bhubaneswar', type: 'city' },
  { slug: 'guwahati', name: 'Guwahati', type: 'city' },
  { slug: 'patna', name: 'Patna', type: 'city' },
  { slug: 'chandigarh', name: 'Chandigarh', type: 'city' },
  { slug: 'surat', name: 'Surat', type: 'city' },
  { slug: 'vadodara', name: 'Vadodara', type: 'city' },
  // International
  { slug: 'new-york', name: 'New York', type: 'city' },
  { slug: 'san-francisco', name: 'San Francisco', type: 'city' },
  { slug: 'los-angeles', name: 'Los Angeles', type: 'city' },
  { slug: 'chicago', name: 'Chicago', type: 'city' },
  { slug: 'boston', name: 'Boston', type: 'city' },
  { slug: 'seattle', name: 'Seattle', type: 'city' },
  { slug: 'austin', name: 'Austin', type: 'city' },
  { slug: 'london', name: 'London', type: 'city' },
  { slug: 'manchester', name: 'Manchester', type: 'city' },
  { slug: 'toronto', name: 'Toronto', type: 'city' },
  { slug: 'vancouver', name: 'Vancouver', type: 'city' },
  { slug: 'sydney', name: 'Sydney', type: 'city' },
  { slug: 'melbourne', name: 'Melbourne', type: 'city' },
  { slug: 'dubai', name: 'Dubai', type: 'city' },
  { slug: 'abu-dhabi', name: 'Abu Dhabi', type: 'city' },
  { slug: 'berlin', name: 'Berlin', type: 'city' },
  { slug: 'munich', name: 'Munich', type: 'city' },
  { slug: 'singapore-city', name: 'Singapore City', type: 'city' },
  { slug: 'kuala-lumpur', name: 'Kuala Lumpur', type: 'city' },
  { slug: 'riyadh', name: 'Riyadh', type: 'city' },
  { slug: 'doha', name: 'Doha', type: 'city' },
  { slug: 'amsterdam', name: 'Amsterdam', type: 'city' },
  { slug: 'paris', name: 'Paris', type: 'city' },
  { slug: 'zurich', name: 'Zurich', type: 'city' },
  { slug: 'tokyo', name: 'Tokyo', type: 'city' },
  { slug: 'seoul', name: 'Seoul', type: 'city' },
  { slug: 'lagos', name: 'Lagos', type: 'city' },
  { slug: 'nairobi', name: 'Nairobi', type: 'city' },
  { slug: 'johannesburg', name: 'Johannesburg', type: 'city' },
  { slug: 'accra', name: 'Accra', type: 'city' },
  { slug: 'manila', name: 'Manila', type: 'city' },
  { slug: 'jakarta', name: 'Jakarta', type: 'city' },

  // ── UNIVERSITIES — INDIA ──
  { slug: 'iit', name: 'IITs', type: 'university' },
  { slug: 'nit', name: 'NITs', type: 'university' },
  { slug: 'iiit', name: 'IIITs', type: 'university' },
  { slug: 'bits-pilani', name: 'BITS Pilani', type: 'university' },
  { slug: 'jntuh', name: 'JNTUH (Jawaharlal Nehru Technological University, Hyderabad)', type: 'university' },
  { slug: 'jntuk', name: 'JNTUK (JNTU Kakinada)', type: 'university' },
  { slug: 'jntua', name: 'JNTUA (JNTU Anantapur)', type: 'university' },
  { slug: 'anna-university', name: 'Anna University', type: 'university' },
  { slug: 'vtu', name: 'VTU (Visvesvaraya Technological University)', type: 'university' },
  { slug: 'delhi-university', name: 'Delhi University (DU)', type: 'university' },
  { slug: 'mumbai-university', name: 'Mumbai University', type: 'university' },
  { slug: 'sppu', name: 'Pune University (SPPU)', type: 'university' },
  { slug: 'osmania-university', name: 'Osmania University (OU)', type: 'university' },
  { slug: 'srm', name: 'SRM Institute of Science and Technology', type: 'university' },
  { slug: 'vit', name: 'VIT Vellore', type: 'university' },
  { slug: 'manipal', name: 'Manipal Academy of Higher Education', type: 'university' },
  { slug: 'amity', name: 'Amity University', type: 'university' },
  { slug: 'lpu', name: 'Lovely Professional University (LPU)', type: 'university' },
  { slug: 'chandigarh-university', name: 'Chandigarh University', type: 'university' },
  { slug: 'aktu', name: 'AKTU (UPTU)', type: 'university' },
  { slug: 'gtu', name: 'Gujarat Technological University (GTU)', type: 'university' },
  { slug: 'rgpv', name: 'RGPV Bhopal', type: 'university' },
  { slug: 'ktu', name: 'APJ Abdul Kalam Technological University (KTU Kerala)', type: 'university' },
  { slug: 'makaut', name: 'MAKAUT West Bengal', type: 'university' },
  { slug: 'bput', name: 'Biju Patnaik University of Technology (BPUT)', type: 'university' },
  { slug: 'andhra-university', name: 'Andhra University (AU)', type: 'university' },
  { slug: 'svu', name: 'Sri Venkateswara University (SVU)', type: 'university' },
  { slug: 'klu', name: 'KLU', type: 'university' },
  { slug: 'gitam', name: 'Gitam University', type: 'university' },
  { slug: 'kiit', name: 'KIIT Bhubaneswar', type: 'university' },
  { slug: 'pes-university', name: 'PES University', type: 'university' },
  { slug: 'christ-university', name: 'Christ University', type: 'university' },
  { slug: 'iit-hyderabad', name: 'IIT Hyderabad', type: 'university' },
  { slug: 'iit-bombay', name: 'IIT Bombay', type: 'university' },
  { slug: 'iit-delhi', name: 'IIT Delhi', type: 'university' },
  { slug: 'iit-madras', name: 'IIT Madras', type: 'university' },
  { slug: 'iit-kharagpur', name: 'IIT Kharagpur', type: 'university' },
  { slug: 'iit-kanpur', name: 'IIT Kanpur', type: 'university' },
  { slug: 'iit-roorkee', name: 'IIT Roorkee', type: 'university' },
  { slug: 'nit-warangal', name: 'NIT Warangal', type: 'university' },
  { slug: 'nit-trichy', name: 'NIT Trichy', type: 'university' },
  { slug: 'nit-surathkal', name: 'NIT Surathkal', type: 'university' },
  { slug: 'nit-calicut', name: 'NIT Calicut', type: 'university' },
  { slug: 'jadavpur-university', name: 'Jadavpur University', type: 'university' },
  { slug: 'psgtech', name: 'PSG College of Technology', type: 'university' },
  { slug: 'ssn-college', name: 'SSN College of Engineering', type: 'university' },
  { slug: 'mit-manipal', name: 'MIT Manipal', type: 'university' },
  { slug: 'bmsce', name: 'BMS College of Engineering', type: 'university' },
  { slug: 'rvce', name: 'RV College of Engineering', type: 'university' },
  { slug: 'msrit', name: 'MS Ramaiah Institute of Technology', type: 'university' },
  { slug: 'cbit', name: 'Chaitanya Bharathi Institute of Technology (CBIT)', type: 'university' },
  { slug: 'vasavi-college', name: 'Vasavi College of Engineering', type: 'university' },
  { slug: 'cmr-college', name: 'CMR College of Engineering', type: 'university' },
  { slug: 'mlrit', name: 'MLR Institute of Technology', type: 'university' },
  { slug: 'griet', name: 'Gokaraju Rangaraju Institute of Engineering and Technology (GRIET)', type: 'university' },
  { slug: 'vignan-university', name: 'Vignan University', type: 'university' },
  { slug: 'rgukt', name: 'Rajiv Gandhi University of Knowledge Technologies (RGUKT IIIT)', type: 'university' },
  { slug: 'mepco-schlenk', name: 'Mepco Schlenk Engineering College', type: 'university' },
  { slug: 'sastra-university', name: 'SASTRA University', type: 'university' },
  { slug: 'sathyabama', name: 'Sathyabama Institute of Science and Technology', type: 'university' },
  { slug: 'velammal', name: 'Velammal Engineering College', type: 'university' },
  { slug: 'kce', name: 'Kongu Engineering College (KCE)', type: 'university' },
  { slug: 'coep', name: 'College of Engineering Pune (COEP)', type: 'university' },
  { slug: 'vjti', name: 'Veermata Jijabai Technological Institute (VJTI)', type: 'university' },
  { slug: 'dj-sanghvi', name: 'Dwarkadas J. Sanghvi College of Engineering', type: 'university' },
  { slug: 'nmims', name: 'NMIMS University', type: 'university' },
  { slug: 'thapar', name: 'Thapar Institute of Engineering and Technology', type: 'university' },
  { slug: 'ptu', name: 'Punjab Technical University (PTU)', type: 'university' },
  { slug: 'kurukshetra-university', name: 'Kurukshetra University', type: 'university' },
  { slug: 'mdu-rohtak', name: 'Maharshi Dayanand University (MDU)', type: 'university' },
  { slug: 'rtmnu', name: 'Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU)', type: 'university' },
  { slug: 'bamu', name: 'Dr. Babasaheb Ambedkar Marathwada University (BAMU)', type: 'university' },
  { slug: 'svnit', name: 'Sardar Vallabhbhai National Institute of Technology (SVNIT)', type: 'university' },
  // USA
  { slug: 'mit', name: 'Massachusetts Institute of Technology (MIT)', type: 'university' },
  { slug: 'stanford', name: 'Stanford University', type: 'university' },
  { slug: 'harvard', name: 'Harvard University', type: 'university' },
  { slug: 'georgia-tech', name: 'Georgia Institute of Technology', type: 'university' },
  { slug: 'uc-berkeley', name: 'UC Berkeley', type: 'university' },
  { slug: 'carnegie-mellon', name: 'Carnegie Mellon University', type: 'university' },
  { slug: 'caltech', name: 'California Institute of Technology', type: 'university' },
  { slug: 'university-of-michigan', name: 'University of Michigan', type: 'university' },
  { slug: 'purdue', name: 'Purdue University', type: 'university' },
  { slug: 'university-of-texas', name: 'University of Texas at Austin', type: 'university' },
  { slug: 'columbia-university', name: 'Columbia University', type: 'university' },
  { slug: 'nyu', name: 'New York University (NYU)', type: 'university' },
  { slug: 'university-of-illinois', name: 'University of Illinois Urbana-Champaign', type: 'university' },
  { slug: 'university-of-washington', name: 'University of Washington', type: 'university' },
  { slug: 'cornell-university', name: 'Cornell University', type: 'university' },
  { slug: 'northeastern-university', name: 'Northeastern University', type: 'university' },
  { slug: 'asu', name: 'Arizona State University (ASU)', type: 'university' },
  { slug: 'boston-university', name: 'Boston University', type: 'university' },
  // UK
  { slug: 'oxford', name: 'University of Oxford', type: 'university' },
  { slug: 'cambridge', name: 'University of Cambridge', type: 'university' },
  { slug: 'imperial-college', name: 'Imperial College London', type: 'university' },
  { slug: 'ucl', name: 'University College London (UCL)', type: 'university' },
  { slug: 'university-of-edinburgh', name: 'University of Edinburgh', type: 'university' },
  { slug: 'kings-college', name: 'King\'s College London', type: 'university' },
  { slug: 'university-of-manchester', name: 'University of Manchester', type: 'university' },
  { slug: 'university-of-birmingham', name: 'University of Birmingham', type: 'university' },
  { slug: 'university-of-bristol', name: 'University of Bristol', type: 'university' },
  { slug: 'university-of-southampton', name: 'University of Southampton', type: 'university' },
  { slug: 'university-of-warwick', name: 'University of Warwick', type: 'university' },
  // Canada
  { slug: 'university-of-toronto', name: 'University of Toronto', type: 'university' },
  { slug: 'ubc', name: 'University of British Columbia (UBC)', type: 'university' },
  { slug: 'mcgill', name: 'McGill University', type: 'university' },
  { slug: 'university-of-waterloo', name: 'University of Waterloo', type: 'university' },
  { slug: 'york-university', name: 'York University', type: 'university' },
  { slug: 'university-of-alberta', name: 'University of Alberta', type: 'university' },
  // Australia
  { slug: 'university-of-melbourne', name: 'University of Melbourne', type: 'university' },
  { slug: 'unsw', name: 'University of New South Wales (UNSW)', type: 'university' },
  { slug: 'anu', name: 'Australian National University (ANU)', type: 'university' },
  { slug: 'university-of-sydney', name: 'University of Sydney', type: 'university' },
  { slug: 'monash-university', name: 'Monash University', type: 'university' },
  { slug: 'rmit', name: 'RMIT University', type: 'university' },
  { slug: 'uts', name: 'University of Technology Sydney (UTS)', type: 'university' },
  // Singapore
  { slug: 'nus', name: 'National University of Singapore (NUS)', type: 'university' },
  { slug: 'ntu-singapore', name: 'Nanyang Technological University (NTU)', type: 'university' },
  { slug: 'smu', name: 'Singapore Management University (SMU)', type: 'university' },
  // UAE
  { slug: 'khalifa-university', name: 'Khalifa University', type: 'university' },
  { slug: 'american-university-sharjah', name: 'American University of Sharjah', type: 'university' },
  { slug: 'uae-university', name: 'UAE University (UAEU)', type: 'university' },
  // Germany
  { slug: 'tu-munich', name: 'Technical University of Munich (TUM)', type: 'university' },
  { slug: 'rwth-aachen', name: 'RWTH Aachen University', type: 'university' },
  { slug: 'tu-berlin', name: 'Technical University of Berlin', type: 'university' },
  { slug: 'heidelberg-university', name: 'Heidelberg University', type: 'university' },
  // Saudi Arabia
  { slug: 'kaust', name: 'King Abdullah University of Science and Technology (KAUST)', type: 'university' },
  { slug: 'ksu', name: 'King Saud University', type: 'university' },
  // Malaysia
  { slug: 'utm', name: 'Universiti Teknologi Malaysia (UTM)', type: 'university' },
  { slug: 'um', name: 'University of Malaya (UM)', type: 'university' },

  // ── ENGINEERING JOB ROLES ──
  { slug: 'software-engineer', name: 'Software Engineer', type: 'role' },
  { slug: 'data-scientist', name: 'Data Scientist', type: 'role' },
  { slug: 'frontend-developer', name: 'Frontend Developer', type: 'role' },
  { slug: 'backend-developer', name: 'Backend Developer', type: 'role' },
  { slug: 'full-stack-developer', name: 'Full Stack Developer', type: 'role' },
  { slug: 'machine-learning-engineer', name: 'Machine Learning Engineer', type: 'role' },
  { slug: 'data-analyst', name: 'Data Analyst', type: 'role' },
  { slug: 'devops-engineer', name: 'DevOps Engineer', type: 'role' },
  { slug: 'cybersecurity-analyst', name: 'Cybersecurity Analyst', type: 'role' },
  { slug: 'cloud-engineer', name: 'Cloud Engineer', type: 'role' },
  { slug: 'product-manager', name: 'Product Manager', type: 'role' },
  { slug: 'ux-designer', name: 'UX Designer', type: 'role' },
  { slug: 'blockchain-developer', name: 'Blockchain Developer', type: 'role' },
  { slug: 'ai-engineer', name: 'AI Engineer', type: 'role' },
  { slug: 'mobile-developer', name: 'Mobile App Developer', type: 'role' },
  { slug: 'embedded-systems-engineer', name: 'Embedded Systems Engineer', type: 'role' },
  { slug: 'nlp-engineer', name: 'NLP Engineer', type: 'role' },
  { slug: 'computer-vision-engineer', name: 'Computer Vision Engineer', type: 'role' },
  { slug: 'site-reliability-engineer', name: 'Site Reliability Engineer (SRE)', type: 'role' },
  { slug: 'database-administrator', name: 'Database Administrator (DBA)', type: 'role' },
  { slug: 'network-engineer', name: 'Network Engineer', type: 'role' },
  { slug: 'business-analyst', name: 'Business Analyst', type: 'role' },
  { slug: 'solution-architect', name: 'Solution Architect', type: 'role' },

  // ── TARGET COMPANIES FOR INTERVIEWS ──
  // Indian IT
  { slug: 'tcs', name: 'TCS (Tata Consultancy Services)', type: 'company' },
  { slug: 'infosys', name: 'Infosys', type: 'company' },
  { slug: 'wipro', name: 'Wipro', type: 'company' },
  { slug: 'cognizant', name: 'Cognizant', type: 'company' },
  { slug: 'tech-mahindra', name: 'Tech Mahindra', type: 'company' },
  { slug: 'zoho', name: 'Zoho', type: 'company' },
  { slug: 'hcl', name: 'HCL Technologies', type: 'company' },
  { slug: 'mphasis', name: 'Mphasis', type: 'company' },
  { slug: 'hexaware', name: 'Hexaware Technologies', type: 'company' },
  { slug: 'mindtree', name: 'Mindtree (LTIMindtree)', type: 'company' },
  { slug: 'persistent-systems', name: 'Persistent Systems', type: 'company' },
  { slug: 'byju', name: 'BYJU\'S', type: 'company' },
  { slug: 'ola', name: 'Ola Cabs', type: 'company' },
  { slug: 'flipkart', name: 'Flipkart', type: 'company' },
  { slug: 'swiggy', name: 'Swiggy', type: 'company' },
  { slug: 'zomato', name: 'Zomato', type: 'company' },
  { slug: 'paytm', name: 'Paytm', type: 'company' },
  { slug: 'phonepe', name: 'PhonePe', type: 'company' },
  { slug: 'razorpay', name: 'Razorpay', type: 'company' },
  { slug: 'freshworks', name: 'Freshworks', type: 'company' },
  // Global Tech Giants
  { slug: 'google', name: 'Google', type: 'company' },
  { slug: 'amazon', name: 'Amazon', type: 'company' },
  { slug: 'microsoft', name: 'Microsoft', type: 'company' },
  { slug: 'meta', name: 'Meta (Facebook)', type: 'company' },
  { slug: 'apple', name: 'Apple', type: 'company' },
  { slug: 'netflix', name: 'Netflix', type: 'company' },
  { slug: 'nvidia', name: 'Nvidia', type: 'company' },
  { slug: 'salesforce', name: 'Salesforce', type: 'company' },
  { slug: 'ibm', name: 'IBM', type: 'company' },
  { slug: 'oracle', name: 'Oracle', type: 'company' },
  { slug: 'adobe', name: 'Adobe', type: 'company' },
  { slug: 'uber', name: 'Uber', type: 'company' },
  { slug: 'linkedin', name: 'LinkedIn', type: 'company' },
  { slug: 'twitter-x', name: 'Twitter / X', type: 'company' },
  { slug: 'airbnb', name: 'Airbnb', type: 'company' },
  { slug: 'stripe', name: 'Stripe', type: 'company' },
  { slug: 'openai', name: 'OpenAI', type: 'company' },
  { slug: 'anthropic', name: 'Anthropic', type: 'company' },
  { slug: 'tesla', name: 'Tesla', type: 'company' },
  // Consulting & Finance
  { slug: 'accenture', name: 'Accenture', type: 'company' },
  { slug: 'capgemini', name: 'Capgemini', type: 'company' },
  { slug: 'deloitte', name: 'Deloitte', type: 'company' },
  { slug: 'mckinsey', name: 'McKinsey & Company', type: 'company' },
  { slug: 'goldman-sachs', name: 'Goldman Sachs', type: 'company' },
  { slug: 'jpmorgan', name: 'JPMorgan Chase', type: 'company' },
  { slug: 'morgan-stanley', name: 'Morgan Stanley', type: 'company' },
  { slug: 'bain', name: 'Bain & Company', type: 'company' },
  { slug: 'bcg', name: 'Boston Consulting Group (BCG)', type: 'company' },
  { slug: 'pwc', name: 'PricewaterhouseCoopers (PwC)', type: 'company' },
  { slug: 'kpmg', name: 'KPMG', type: 'company' },
  { slug: 'ey', name: 'Ernst & Young (EY)', type: 'company' },
];
