"use client";

import { useState, useRef } from "react";
import { Loader2, Map, ChevronRight, FileText, BarChart3, Target, BookOpen, Download, Copy, Cpu, Layers, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import { ModelSelector, AIModel } from "@/components/ModelSelector";

export default function CareerGuidancePage() {
  const [goal, setGoal] = useState("");
  const [background, setBackground] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [roadmap, setRoadmap] = useState("");
  const [activeView, setActiveView] = useState<"text" | "visual">("text");
  const [preferredModel, setPreferredModel] = useState<AIModel>("deepseek");
  const roadmapRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!goal) return;
    setIsLoading(true);
    setRoadmap("");
    try {
      const res = await fetch("/api/career-roadmap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal, background, preferredModel }),
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      setRoadmap(data.roadmap);
    } catch (error) {
      alert("Error generating roadmap. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow || !roadmap) return;

    // Convert markdown to simple HTML for clean PDF output
    const htmlContent = roadmap
      .replace(/^## (.+)$/gm, "<h2>$1</h2>")
      .replace(/^### (.+)$/gm, "<h3>$1</h3>")
      .replace(/^# (.+)$/gm, "<h1>$1</h1>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/^- (.+)$/gm, "<li>$1</li>")
      .replace(/^\* (.+)$/gm, "<li>$1</li>")
      .replace(/^(\d+)\. (.+)$/gm, "<li>$2</li>")
      .replace(/((<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/^(?!<[hul]).+/gm, (m) => m ? m : "");

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Career Roadmap - ${goal}</title>
        <meta charset="utf-8">
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, sans-serif; padding: 40px; color: #111; line-height: 1.8; }
          .header { border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 28px; }
          .header h1 { font-size: 26px; font-weight: 900; color: #4f46e5; }
          .header p { color: #6b7280; font-size: 13px; margin-top: 6px; }
          h2 { font-size: 18px; font-weight: 700; color: #1e1b4b; margin: 24px 0 10px; padding-left: 10px; border-left: 4px solid #4f46e5; }
          h3 { font-size: 15px; font-weight: 600; color: #312e81; margin: 16px 0 6px; }
          p { margin-bottom: 10px; color: #374151; }
          ul { padding-left: 22px; margin: 8px 0 16px; }
          li { margin-bottom: 5px; color: #374151; }
          strong { font-weight: 700; color: #111827; }
          .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Career Roadmap: ${goal}</h1>
          <p>Generated by GraduateNex AI Career Coach &bull; Background: ${background || "Recent Graduate"}</p>
        </div>
        <div>${htmlContent}</div>
        <div class="footer">Generated by GraduateNex &bull; graduatenex.online</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 600);
  };

  const parseVisualPhases = (text: string) => {
    const lines = text.split("\n");
    const phases: { title: string; items: string[], description: string }[] = [];
    let current: { title: string; items: string[], description: string } | null = null;
    let inList = false;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      const isHeader = trimmed.startsWith("##") || trimmed.startsWith("###");
      const isBoldPhase = trimmed.startsWith("**Phase") || trimmed.startsWith("**Month") || trimmed.startsWith("**Step");
      
      if (isHeader || isBoldPhase) {
        const titleText = trimmed.replace(/^#+\s*/, "").replace(/\*\*/g, "").trim();
        // Skip boilerplate intro titles
        if (titleText.toLowerCase().includes("overview") || titleText.toLowerCase() === "career roadmap") continue;

        if (current && (current.items.length > 0 || current.description)) {
            phases.push(current);
        }
        current = { title: titleText, items: [], description: "" };
        inList = false;
      } else if (trimmed.startsWith("-") || trimmed.startsWith("* ") || trimmed.match(/^\d+\.\s/)) {
        if (current) {
          const itemText = trimmed.replace(/^[-*]\s*/, "").replace(/^\d+\.\s*/, "").replace(/\*\*/g, "").trim();
          if (itemText) {
             current.items.push(itemText);
          }
          inList = true;
        }
      } else {
        if (current && !inList && !current.description) {
           current.description = trimmed.replace(/\*\*/g, "");
        }
      }
    }
    if (current && (current.items.length > 0 || current.description)) phases.push(current);
    
    return phases.filter(p => p.items.length > 0 || p.description.length > 10);
  };

  const phaseColors = [
    "from-violet-500 to-indigo-600",
    "from-indigo-500 to-blue-600",
    "from-blue-500 to-cyan-600",
    "from-cyan-500 to-teal-600",
    "from-teal-500 to-emerald-600",
    "from-emerald-500 to-green-600",
    "from-orange-500 to-amber-600",
    "from-rose-500 to-pink-600",
  ];

  const phases = roadmap ? parseVisualPhases(roadmap) : [];

  return (
    <div className="min-h-screen bg-muted/30 pb-20">
      <div className="bg-gradient-to-br from-indigo-900 to-purple-900 text-white py-16 border-b relative overflow-hidden">
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: "radial-gradient(circle at 20% 50%, white 1px, transparent 1px), radial-gradient(circle at 80% 20%, white 1px, transparent 1px)", backgroundSize: "40px 40px" }} />
        <div className="container mx-auto px-4 md:px-6 max-w-5xl relative z-10">
          <Link href="/study" className="text-indigo-200 hover:text-white font-semibold mb-4 inline-flex items-center gap-1">
            <ChevronRight className="rotate-180 w-4 h-4" /> Back to Study Hub
          </Link>
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl mb-4">
            AI Career <span className="text-purple-300">Roadmap Generator</span>
          </h1>
          <p className="text-xl text-indigo-100 max-w-2xl">
            Get a detailed, personalized career roadmap powered by Groq AI — with a visual timeline & downloadable PDF.
          </p>
        </div>
      </div>

      <div className="container mx-auto px-4 md:px-6 mt-10 max-w-6xl">
        <div className="grid lg:grid-cols-[340px_1fr] gap-8">

          {/* Form */}
          <div className="space-y-5">
            <form onSubmit={handleGenerate} className="bg-white dark:bg-zinc-900 p-6 rounded-2xl border shadow-sm space-y-5">
              <div>
                <label className="block text-sm font-semibold mb-2 flex items-center gap-2"><Target className="w-4 h-4 text-indigo-500" /> Dream Role</label>
                <input required placeholder="e.g. Senior AI Engineer" value={goal} onChange={e => setGoal(e.target.value)}
                  className="w-full p-3 rounded-xl border bg-gray-50 outline-none focus:ring-2 focus:ring-purple-500 text-sm" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-2 flex items-center gap-2"><BookOpen className="w-4 h-4 text-indigo-500" /> Your Background <span className="text-gray-400 font-normal">(optional)</span></label>
                <textarea rows={3} placeholder="e.g. 3rd year CS student, know basic Python"
                  value={background} onChange={e => setBackground(e.target.value)}
                  className="w-full p-3 rounded-xl border bg-gray-50 outline-none focus:ring-2 focus:ring-purple-500 text-sm" />
              </div>
              <div className="mb-4">
                <ModelSelector value={preferredModel} onChange={setPreferredModel} />
              </div>
              <Button type="submit" disabled={isLoading} className="w-full h-12 font-bold bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl">
                {isLoading ? <Loader2 className="animate-spin mr-2 h-5 w-5" /> : <Map className="mr-2 h-5 w-5" />}
                {isLoading ? "Generating..." : "Generate Roadmap"}
              </Button>
            </form>

            {roadmap && (
              <div className="bg-white dark:bg-zinc-900 p-5 rounded-2xl border shadow-sm space-y-3">
                <p className="font-bold text-sm flex items-center gap-2"><Layers className="w-4 h-4 text-indigo-500" /> Export Options</p>
                <Button onClick={handleDownloadPDF} variant="outline" className="w-full justify-start gap-2">
                  <Download className="w-4 h-4 text-red-500" /> Download as PDF
                </Button>
                <Button onClick={() => {
                  navigator.clipboard.writeText(roadmap);
                  alert("Roadmap copied to clipboard!");
                }} variant="outline" className="w-full justify-start gap-2">
                  <Copy className="w-4 h-4 text-blue-500" /> Copy to Clipboard
                </Button>
              </div>
            )}
          </div>

          {/* Results */}
          <div className="bg-white dark:bg-zinc-900 rounded-2xl border shadow-sm overflow-hidden">
            {!roadmap && !isLoading && (
              <div className="h-full flex flex-col items-center justify-center text-center text-muted-foreground opacity-50 p-12 min-h-[400px]">
                <Map className="w-20 h-20 mb-4" />
                <h3 className="text-xl font-bold">Your Roadmap Awaits</h3>
                <p>Fill out the form on the left to generate your step-by-step career guide.</p>
              </div>
            )}

            {isLoading && (
              <div className="h-full flex flex-col items-center justify-center text-center text-indigo-500 min-h-[400px]">
                <Cpu className="w-16 h-16 animate-pulse mb-4" />
                <h3 className="text-xl font-bold animate-pulse">Analyzing career path...</h3>
                <p className="text-sm text-muted-foreground mt-2">Groq AI is building your personalized roadmap</p>
              </div>
            )}

            {roadmap && !isLoading && (
              <div>
                {/* View Toggle */}
                <div className="flex border-b">
                  <button onClick={() => setActiveView("text")} className={`flex-1 py-4 text-sm font-bold flex items-center justify-center gap-2 transition-colors ${activeView === "text" ? "bg-indigo-50 text-indigo-700 border-b-2 border-indigo-600" : "text-muted-foreground hover:bg-muted/50"}`}>
                    <FileText className="w-4 h-4" /> Detailed Text
                  </button>
                  <button onClick={() => setActiveView("visual")} className={`flex-1 py-4 text-sm font-bold flex items-center justify-center gap-2 transition-colors ${activeView === "visual" ? "bg-indigo-50 text-indigo-700 border-b-2 border-indigo-600" : "text-muted-foreground hover:bg-muted/50"}`}>
                    <BarChart3 className="w-4 h-4" /> Visual Timeline
                  </button>
                </div>

                {/* Text View */}
                {activeView === "text" && (
                  <div className="p-8 animate-in fade-in duration-300">
                    <div ref={roadmapRef} className="prose dark:prose-invert max-w-none prose-headings:text-indigo-800 dark:prose-headings:text-indigo-300 prose-h2:border-l-4 prose-h2:border-indigo-500 prose-h2:pl-3 text-left">
                      <ReactMarkdown>{roadmap}</ReactMarkdown>
                    </div>
                  </div>
                )}

                {/* Visual Timeline View */}
                {activeView === "visual" && (
                  <div className="p-8 bg-slate-50 dark:bg-zinc-950 animate-in fade-in duration-300 min-h-[600px]">
                    <div className="text-center mb-12">
                      <h2 className="text-3xl font-black mb-2 flex items-center justify-center gap-3 text-slate-800 dark:text-slate-100">
                        <Map className="w-8 h-8 text-indigo-500" /> 
                        Your Visual Roadmap
                      </h2>
                      <p className="text-slate-500">A step-by-step journey to your dream role</p>
                    </div>

                    {phases.length > 0 ? (
                      <div className="relative max-w-4xl mx-auto py-10">
                        {/* Central Vertical Line (hidden on mobile, visible on md+) */}
                        <div className="absolute left-8 md:left-1/2 top-0 bottom-0 w-1 bg-gradient-to-b from-indigo-500 via-purple-500 to-pink-500 transform md:-translate-x-1/2 rounded-full" />

                        <div className="space-y-12">
                          {phases.map((phase, i) => {
                            const isEven = i % 2 === 0;
                            return (
                              <div key={i} className="relative flex flex-col md:flex-row items-center justify-between animate-in fade-in slide-in-from-bottom-8" style={{ animationDelay: `${i * 150}ms`, animationFillMode: "both" }}>
                                
                                {/* Left Side */}
                                <div className={`hidden md:flex w-5/12 ${isEven ? 'justify-end pr-10' : 'justify-start pl-10 order-3'}`}>
                                  {isEven && (
                                    <div className="bg-white dark:bg-zinc-900 p-6 rounded-2xl shadow-xl border border-indigo-100 dark:border-zinc-800 hover:-translate-y-1 hover:shadow-2xl transition-all duration-300 w-full text-right group">
                                      <h3 className="font-bold text-xl mb-3 text-indigo-700 dark:text-indigo-400 group-hover:text-indigo-600 transition-colors">{phase.title}</h3>
                                      {phase.description && <p className="text-sm text-slate-500 dark:text-slate-400 mb-4 leading-relaxed">{phase.description}</p>}
                                      {phase.items.length > 0 && (
                                        <ul className="space-y-2 inline-flex flex-col items-end">
                                          {phase.items.slice(0, 6).map((item, j) => (
                                            <li key={j} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300 flex-row-reverse text-right">
                                              <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                              <span className="leading-snug">{item}</span>
                                            </li>
                                          ))}
                                        </ul>
                                      )}
                                    </div>
                                  )}
                                </div>

                                {/* Center Node */}
                                <div className="absolute left-8 md:left-1/2 transform -translate-x-1/2 flex items-center justify-center z-10 md:order-2">
                                  <div className={`w-14 h-14 rounded-full bg-gradient-to-br ${phaseColors[i % phaseColors.length]} shadow-xl flex items-center justify-center text-white font-black text-xl ring-4 ring-white dark:ring-zinc-900 transition-transform duration-300 hover:scale-110`}>
                                    {i + 1}
                                  </div>
                                </div>

                                {/* Right Side & Mobile */}
                                <div className={`w-full md:w-5/12 pl-24 md:pl-0 ${!isEven ? 'md:pr-10 md:order-1 hidden md:flex md:justify-end' : 'md:pl-10 md:order-3'}`}>
                                  {/* Mobile Card (always visible) and Desktop Odd Card */}
                                  <div className={`bg-white dark:bg-zinc-900 p-6 rounded-2xl shadow-xl border ${isEven ? 'border-indigo-100 dark:border-zinc-800 md:opacity-0 md:pointer-events-none' : 'border-purple-100 dark:border-zinc-800'} hover:-translate-y-1 hover:shadow-2xl transition-all duration-300 w-full text-left group`}>
                                    <h3 className={`font-bold text-xl mb-3 ${isEven ? 'text-indigo-700 dark:text-indigo-400' : 'text-purple-700 dark:text-purple-400'}`}>{phase.title}</h3>
                                    {phase.description && <p className="text-sm text-slate-500 dark:text-slate-400 mb-4 leading-relaxed">{phase.description}</p>}
                                    {phase.items.length > 0 && (
                                      <ul className="space-y-2">
                                          {phase.items.slice(0, 6).map((item, j) => (
                                            <li key={j} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300">
                                              <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                                              <span className="leading-snug">{item}</span>
                                            </li>
                                          ))}
                                        </ul>
                                      )}
                                    </div>
                                </div>

                              </div>
                            );
                          })}
                        </div>
                        
                        <div className="mt-16 text-center">
                           <div className="inline-flex items-center justify-center p-1 rounded-full bg-slate-200 dark:bg-zinc-800">
                              <div className="px-4 py-2 rounded-full text-sm font-semibold text-slate-600 dark:text-slate-300 bg-white dark:bg-zinc-700 shadow-sm">
                                You've reached the end of the visual timeline!
                              </div>
                           </div>
                           <p className="mt-4 text-sm text-slate-400">Switch to "Detailed Text" view to see any additional tips and resources.</p>
                        </div>
                      </div>
                    ) : (
                      <div className="text-center text-slate-400 py-16">
                        <Map className="w-16 h-16 mx-auto mb-4 opacity-20" />
                        <p>Switch to Detailed Text view to see your full roadmap</p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
