"use client";

import { useState, useRef } from "react";
import { Loader2, Map, ChevronRight, Share2, Download, FileText, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import ReactMarkdown from "react-markdown";

export default function CareerGuidancePage() {
  const [goal, setGoal] = useState("");
  const [background, setBackground] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [roadmap, setRoadmap] = useState("");
  const [activeView, setActiveView] = useState<"text" | "visual">("text");
  const roadmapRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!goal) return;
    setIsLoading(true);
    setRoadmap("");
    try {
      const res = await fetch("/api/career-roadmap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal, background }),
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      setRoadmap(data.roadmap);
    } catch (error) {
      alert("Error generating roadmap. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const content = roadmapRef.current?.innerHTML || "";
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Career Roadmap - ${goal}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Inter', sans-serif; padding: 40px; color: #111; line-height: 1.7; }
          h1 { font-size: 28px; font-weight: 900; color: #4f46e5; margin-bottom: 8px; }
          .meta { color: #6b7280; font-size: 14px; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #e5e7eb; }
          h2 { font-size: 20px; font-weight: 700; color: #1e1b4b; margin: 28px 0 12px; padding-left: 12px; border-left: 4px solid #4f46e5; }
          h3 { font-size: 16px; font-weight: 600; color: #312e81; margin: 20px 0 8px; }
          p { margin-bottom: 12px; color: #374151; }
          ul, ol { padding-left: 24px; margin-bottom: 16px; }
          li { margin-bottom: 6px; color: #374151; }
          strong { color: #111827; font-weight: 700; }
          .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
        </style>
      </head>
      <body>
        <h1>🗺️ Career Roadmap: ${goal}</h1>
        <div class="meta">Generated by GraduateNex AI Career Coach &bull; Background: ${background || "Recent Graduate"}</div>
        <div>${content}</div>
        <div class="footer">Generated by GraduateNex &bull; graduatenex.online</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  // Parse roadmap text into visual phases
  const parseVisualPhases = (text: string) => {
    const lines = text.split("\n");
    const phases: { title: string; items: string[] }[] = [];
    let current: { title: string; items: string[] } | null = null;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed.startsWith("##") || trimmed.startsWith("**Month") || trimmed.startsWith("**Phase") || trimmed.startsWith("## Phase") || trimmed.startsWith("## Month")) {
        if (current) phases.push(current);
        current = { title: trimmed.replace(/^#+\s*/, "").replace(/\*\*/g, ""), items: [] };
      } else if (trimmed.startsWith("-") || trimmed.startsWith("*") || trimmed.match(/^\d+\./)) {
        if (current) current.items.push(trimmed.replace(/^[-*]\s*/, "").replace(/^\d+\.\s*/, "").replace(/\*\*/g, ""));
      }
    }
    if (current) phases.push(current);
    return phases.slice(0, 8);
  };

  const phaseColors = [
    "from-violet-500 to-indigo-600",
    "from-indigo-500 to-blue-600",
    "from-blue-500 to-cyan-600",
    "from-cyan-500 to-teal-600",
    "from-teal-500 to-emerald-600",
    "from-emerald-500 to-green-600",
    "from-orange-500 to-amber-600",
    "from-rose-500 to-pink-600",
  ];

  const phases = roadmap ? parseVisualPhases(roadmap) : [];

  return (
    <div className="min-h-screen bg-muted/30 pb-20">
      <div className="bg-gradient-to-br from-indigo-900 to-purple-900 text-white py-16 border-b relative overflow-hidden">
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: "radial-gradient(circle at 20% 50%, white 1px, transparent 1px), radial-gradient(circle at 80% 20%, white 1px, transparent 1px)", backgroundSize: "40px 40px" }} />
        <div className="container mx-auto px-4 md:px-6 max-w-5xl relative z-10">
          <Link href="/study" className="text-indigo-200 hover:text-white font-semibold mb-4 inline-flex items-center gap-1">
            <ChevronRight className="rotate-180 w-4 h-4" /> Back to Study Hub
          </Link>
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl mb-4">
            AI Career <span className="text-purple-300">Roadmap Generator</span>
          </h1>
          <p className="text-xl text-indigo-100 max-w-2xl">
            Get a detailed, personalized career roadmap powered by Groq AI — with a visual timeline & downloadable PDF.
          </p>
        </div>
      </div>

      <div className="container mx-auto px-4 md:px-6 mt-10 max-w-6xl">
        <div className="grid lg:grid-cols-[340px_1fr] gap-8">

          {/* Form */}
          <div className="space-y-5">
            <form onSubmit={handleGenerate} className="bg-white dark:bg-zinc-900 p-6 rounded-2xl border shadow-sm space-y-5">
              <div>
                <label className="block text-sm font-semibold mb-2">🎯 Dream Role</label>
                <input required placeholder="e.g. Senior AI Engineer" value={goal} onChange={e => setGoal(e.target.value)}
                  className="w-full p-3 rounded-xl border bg-gray-50 outline-none focus:ring-2 focus:ring-purple-500 text-sm" />
              </div>
              <div>
                <label className="block text-sm font-semibold mb-2">📚 Your Background <span className="text-gray-400 font-normal">(optional)</span></label>
                <textarea rows={3} placeholder="e.g. 3rd year CS student, know basic Python"
                  value={background} onChange={e => setBackground(e.target.value)}
                  className="w-full p-3 rounded-xl border bg-gray-50 outline-none focus:ring-2 focus:ring-purple-500 text-sm" />
              </div>
              <Button type="submit" disabled={isLoading} className="w-full h-12 font-bold bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl">
                {isLoading ? <Loader2 className="animate-spin mr-2 h-5 w-5" /> : <Map className="mr-2 h-5 w-5" />}
                {isLoading ? "Generating..." : "Generate Roadmap"}
              </Button>
            </form>

            {roadmap && (
              <div className="bg-white dark:bg-zinc-900 p-5 rounded-2xl border shadow-sm space-y-3">
                <p className="font-bold text-sm">📥 Export Options</p>
                <Button onClick={handleDownloadPDF} variant="outline" className="w-full justify-start gap-2">
                  <FileText className="w-4 h-4 text-red-500" /> Download as PDF
                </Button>
                <Button onClick={() => {
                  navigator.clipboard.writeText(roadmap);
                  alert("Roadmap copied to clipboard!");
                }} variant="outline" className="w-full justify-start gap-2">
                  <Share2 className="w-4 h-4 text-blue-500" /> Copy to Clipboard
                </Button>
              </div>
            )}
          </div>

          {/* Results */}
          <div className="bg-white dark:bg-zinc-900 rounded-2xl border shadow-sm overflow-hidden">
            {!roadmap && !isLoading && (
              <div className="h-full flex flex-col items-center justify-center text-center text-muted-foreground opacity-50 p-12 min-h-[400px]">
                <Map className="w-20 h-20 mb-4" />
                <h3 className="text-xl font-bold">Your Roadmap Awaits</h3>
                <p>Fill out the form on the left to generate your step-by-step career guide.</p>
              </div>
            )}

            {isLoading && (
              <div className="h-full flex flex-col items-center justify-center text-center text-indigo-500 min-h-[400px]">
                <Loader2 className="w-16 h-16 animate-spin mb-4" />
                <h3 className="text-xl font-bold animate-pulse">Analyzing career path...</h3>
                <p className="text-sm text-muted-foreground mt-2">Groq AI is building your personalized roadmap</p>
              </div>
            )}

            {roadmap && !isLoading && (
              <div>
                {/* View Toggle */}
                <div className="flex border-b">
                  <button onClick={() => setActiveView("text")} className={`flex-1 py-4 text-sm font-bold flex items-center justify-center gap-2 transition-colors ${activeView === "text" ? "bg-indigo-50 text-indigo-700 border-b-2 border-indigo-600" : "text-muted-foreground hover:bg-muted/50"}`}>
                    <FileText className="w-4 h-4" /> Detailed Text
                  </button>
                  <button onClick={() => setActiveView("visual")} className={`flex-1 py-4 text-sm font-bold flex items-center justify-center gap-2 transition-colors ${activeView === "visual" ? "bg-indigo-50 text-indigo-700 border-b-2 border-indigo-600" : "text-muted-foreground hover:bg-muted/50"}`}>
                    <BarChart3 className="w-4 h-4" /> Visual Timeline
                  </button>
                </div>

                {/* Text View */}
                {activeView === "text" && (
                  <div className="p-8 animate-in fade-in duration-300">
                    <div ref={roadmapRef} className="prose dark:prose-invert max-w-none prose-headings:text-indigo-800 dark:prose-headings:text-indigo-300 prose-h2:border-l-4 prose-h2:border-indigo-500 prose-h2:pl-3">
                      <ReactMarkdown>{roadmap}</ReactMarkdown>
                    </div>
                  </div>
                )}

                {/* Visual Timeline View */}
                {activeView === "visual" && (
                  <div className="p-6 animate-in fade-in duration-300">
                    <h2 className="text-xl font-bold mb-6 text-center">🗺️ Visual Career Roadmap</h2>
                    {phases.length > 0 ? (
                      <div className="relative">
                        {/* Vertical Line */}
                        <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-gradient-to-b from-violet-500 to-pink-500 hidden md:block" />

                        <div className="space-y-6">
                          {phases.map((phase, i) => (
                            <div key={i} className="flex gap-4 animate-in fade-in slide-in-from-left-4" style={{ animationDelay: `${i * 100}ms` }}>
                              {/* Step Number */}
                              <div className={`shrink-0 w-12 h-12 rounded-full bg-gradient-to-br ${phaseColors[i % phaseColors.length]} text-white font-black text-lg flex items-center justify-center shadow-lg z-10`}>
                                {i + 1}
                              </div>
                              {/* Card */}
                              <div className="flex-1 bg-white dark:bg-zinc-800 border rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
                                <h3 className="font-bold text-base mb-3 text-gray-900 dark:text-white">{phase.title}</h3>
                                {phase.items.length > 0 && (
                                  <ul className="space-y-1.5">
                                    {phase.items.slice(0, 5).map((item, j) => (
                                      <li key={j} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-300">
                                        <span className="mt-1 w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0" />
                                        {item.substring(0, 100)}{item.length > 100 ? "..." : ""}
                                      </li>
                                    ))}
                                  </ul>
                                )}
                              </div>
                            </div>
                          ))}
                        </div>
                        <div className="mt-8 text-center text-sm text-muted-foreground">
                          Switch to "Detailed Text" view for the complete roadmap
                        </div>
                      </div>
                    ) : (
                      <div className="text-center text-muted-foreground py-8">
                        <p>Switch to Detailed Text view to see your full roadmap</p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
